# Generated by Django 4.2.7 on 2025-10-05 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='real_estate_app.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(choices=[('warehouse', '🏭 Warehouse'), ('office', '🏢 Office'), ('retail', '🛍️ Retail'), ('industrial', '🏗️ Industrial'), ('mixed', '🔀 Mixed Use')], max_length=20)),
                ('status', models.CharField(choices=[('active', '✅ Active'), ('inactive', '❌ Inactive'), ('draft', '📝 Draft')], default='active', max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('build_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='real_estate_app.company')),
            ],
            options={
                'verbose_name': 'Property Object',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(choices=[('entire_object', '🏢 Entire Object'), ('unit', '📦 Unit')], max_length=20)),
                ('offer_type', models.CharField(choices=[('sale', '💰 Sale'), ('lease', '📄 Lease'), ('both', '💼 Sale & Lease')], default='lease', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('whs_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Warehouse Area (m²)')),
                ('mez_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mezzanine Area (m²)')),
                ('office_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Office Area (m²)')),
                ('tech_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Technical Area (m²)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Height (m)')),
                ('column_grid', models.CharField(blank=True, max_length=50)),
                ('floor_load', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Floor Load (t/m²)')),
                ('floor_type', models.CharField(blank=True, choices=[('concrete', 'Бетон'), ('tile', 'Плитка'), ('asphalt', 'Асфальт'), ('poured', 'Наливные')], max_length=20)),
                ('docks_amount', models.IntegerField(default=0, verbose_name='Docks')),
                ('fire_alarm', models.BooleanField(default=True)),
                ('sprinkler_system', models.BooleanField(default=True)),
                ('smoke_remove', models.BooleanField(default=True)),
                ('hydrants', models.BooleanField(default=False)),
                ('special_fire_system', models.BooleanField(default=False)),
                ('ventilation', models.BooleanField(default=False)),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Electricity (kW)')),
                ('water', models.CharField(choices=[('municipal', 'Municipal'), ('private', 'Private'), ('none', 'None')], default='none', max_length=20)),
                ('heating', models.CharField(choices=[('municipal', 'Municipal'), ('private', 'Private'), ('none', 'None')], default='none', max_length=20)),
                ('sew', models.CharField(choices=[('municipal', 'Municipal'), ('private', 'Private'), ('none', 'None')], default='none', max_length=20, verbose_name='Sewage')),
                ('floorplan_image', models.ImageField(blank=True, null=True, upload_to='floorplans/')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lease_price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate_app.contact')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='real_estate_app.object')),
                ('parent_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_vacancies', to='real_estate_app.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='object_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate_app.object')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_app.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company', 'is_primary'), name='unique_primary_contact'),
        ),
    ]
