# Generated by Django 4.2.7 on 2025-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_object_latitude_object_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('warehouse', '🏭 Warehouse'), ('mixed', '🔀 Mixed Use')], default='warehouse', max_length=20),
        ),
    ]
