# Generated by Django 4.2.7 on 2025-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_alter_object_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(choices=[('msk', 'Москва'), ('spb', 'Санкт-Петербург')], default='spb', max_length=15),
        ),
    ]
