# Generated by Django 4.2.7 on 2025-10-05 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0004_alter_object_address_alter_object_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
